# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [ ]:
import pandas as pd
import numpy as np
a = {
    "Name":["Alice","Bob","Charlie","David","Emma"],
     "Age":[25,30,35,40,22],
    "Score":[88,92,79,85,95]
}

b = pd.DataFrame(a)
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [ ]:
b['Age'] > 30

0    False
1    False
2     True
3     True
4    False
Name: Age, dtype: bool

In [ ]:
b[b['Age'] > 30]

      Name  Age  Score
2  Charlie   35     79
3    David   40     85

In [ ]:
# multiple conditions (AND):Age > 25 AND Score > 85
b[(b['Age'] > 25) & (b['Score'] > 85)]

  Name  Age  Score
1  Bob   30     92

In [ ]:
# multiple conditions (OR):Age < 25 OR Score > 90
b[(b['Age'] < 25 ) | (b['Score'] > 95)]

   Name  Age  Score
4  Emma   22     95

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [3]:
# Simple quiry: Age > 25
import pandas as pd
import numpy as np
a = {
    "Name":["Alice","Bob","Charlie","David","Emma"],
     "Age":[25,30,35,40,22],
    "Score":[88,92,79,85,95]
}

b = pd.DataFrame(a)
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [4]:
b.query("Age > 25")

      Name  Age  Score
1      Bob   30     92
2  Charlie   35     79
3    David   40     85

In [5]:
b.query("Age < 35 and Score >= 85")

    Name  Age  Score
0  Alice   25     88
1    Bob   30     92
4   Emma   22     95

In [ ]:
# Using a Python variable inside a query (with @)
b.query("Score > @ hold")

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [7]:
b

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [8]:
b['Name'].str.lower()

0      alice
1        bob
2    charlie
3      david
4       emma
Name: Name, dtype: object

In [9]:
b['Name'].str.upper()

0      ALICE
1        BOB
2    CHARLIE
3      DAVID
4       EMMA
Name: Name, dtype: object

In [10]:
b['Name'].str.replace("Charlie","Charles")

0      Alice
1        Bob
2    Charles
3      David
4       Emma
Name: Name, dtype: object

In [11]:
b['Name'].str.startswith("D")

0    False
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.