# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [2]:
import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}

# 2. Create DataFrame
df = pd.DataFrame(data)

# 3. Display DataFrame
print(df)
df.dtypes

   OrderID   OrderDate Customer  Amount
0     1001  2024-01-05    Alice     250
1     1002  2024/01/12      Bob     400
2     1003  15-01-2024  Charlie     150
3     1004  2024-01-20    David     300
4     1005    20240125     Emma     500

OrderID       int64
OrderDate    object
Customer     object
Amount        int64
dtype: object

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [5]:
import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}
df.set_index("OrderDate")

            OrderID Customer  Amount
OrderDate
2024-01-05     1001    Alice     250
2024/01/12     1002      Bob     400
15-01-2024     1003  Charlie     150
2024-01-20     1004    David     300
20240125       1005     Emma     500

## mini-project

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [ ]:

# 1️⃣ Create a dataset of website visits (string dates + visit counts)

# 2️⃣ Convert VisitDate to datetime
# Write your code here

# 3️⃣ Set VisitDate as the index
# Write your code here

# 4️⃣ Resample to get total visitors per month
# Write your code here

# 5️⃣ Resample to get average visitors per week
# Write your code here

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.