# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Math": [88, 75, 92, 60, 85],
    "Science": [90, 80, 78, 70, 95]
}

df = pd.DataFrame(data)

df

      Name  Math  Science
0    Alice    88       90
1      Bob    75       80
2  Charlie    92       78
3    David    60       70
4     Emma    85       95

In [3]:
df['Total Marks'] = df[['Math','Science']].apply(lambda row : row.sum(),axis = 1)
df

      Name  Math  Science  Total Marks
0    Alice    88       90          178
1      Bob    75       80          155
2  Charlie    92       78          170
3    David    60       70          130
4     Emma    85       95          180

In [4]:
col_mean = df[['Math', 'Science']].apply(lambda col: col.mean())
col_mean

Math       80.0
Science    82.6
dtype: float64

In [8]:
def to_grade(s):
  if s >= 90:
    return "A"
  elif s >= 80:
    return "B"
  elif s >= 70:
    return "C"
  else:
    return "D"
df['Math'] = df['Math'].apply(to_grade)

In [7]:
df

      Name  Math  Science  Total Marks
0    Alice    88       90          178
1      Bob    75       80          155
2  Charlie    92       78          170
3    David    60       70          130
4     Emma    85       95          180

In [9]:
df

      Name Math  Science  Total Marks
0    Alice    B       90          178
1      Bob    C       80          155
2  Charlie    A       78          170
3    David    D       70          130
4     Emma    B       95          180

In [11]:
df['Name'] = df['Name'].map(str.lower)
df

      Name Math  Science  Total Marks
0    alice    B       90          178
1      bob    C       80          155
2  charlie    A       78          170
3    david    D       70          130
4     emma    B       95          180